/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Gustavo Rian
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospedes = new javax.swing.JMenuItem();
        menuConHospedes = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuartos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuConProdutos = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuCadServicos = new javax.swing.JMenuItem();
        menuConServicos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadReservas = new javax.swing.JMenuItem();
        menuConReservas = new javax.swing.JMenuItem();
        menuFinReservas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuVenProdutos = new javax.swing.JMenuItem();
        menuVenServicos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        menuCadConPagar = new javax.swing.JMenuItem();
        menuConConPagar = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        menuCadConReceber = new javax.swing.JMenuItem();
        menuConConReceber = new javax.swing.JMenuItem();
        menuBalanco = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        menuRelaFinContPagar = new javax.swing.JMenuItem();
        menuRelaFinContReceber = new javax.swing.JMenuItem();
        menuRelaFinBalanco = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        menuRelaResQDisp = new javax.swing.JMenuItem();
        menuRelaResQOcup = new javax.swing.JMenuItem();
        menuRelaResRFut = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        menuRelaVenProdutos = new javax.swing.JMenuItem();
        menuRelaVenServicos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuFazBackup = new javax.swing.JMenuItem();
        menuResBackup = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        menuFerraTelaAddFundo = new javax.swing.JMenuItem();
        menuFerraTelaRemovImg = new javax.swing.JMenuItem();
        menuFerraTelaResPadrao = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        jMenu1.setText("Cadastros    |");

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        jMenu9.setText("Hospedes");

        menuCadHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        menuCadHospedes.setText("Cadastrar");
        jMenu9.add(menuCadHospedes);

        menuConHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        menuConHospedes.setText("Consultar");
        jMenu9.add(menuConHospedes);

        jMenu1.add(jMenu9);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        jMenu10.setText("Quartos");

        menuCadQuartos.setText("Cadastrar");
        jMenu10.add(menuCadQuartos);

        menuConQuartos.setText("Consultar");
        jMenu10.add(menuConQuartos);

        jMenu1.add(jMenu10);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_funcionario.png"))); // NOI18N
        jMenu6.setText("Funcionários");

        menuCadFuncionarios.setText("Cadastrar");
        jMenu6.add(menuCadFuncionarios);

        menuConFuncionarios.setText("Consultar");
        jMenu6.add(menuConFuncionarios);

        jMenu1.add(jMenu6);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_fornecedor.png"))); // NOI18N
        jMenu11.setText("Fornecedores");

        menuCadFornecedores.setText("Cadastrar");
        jMenu11.add(menuCadFornecedores);

        menuConFornecedores.setText("Consultar");
        jMenu11.add(menuConFornecedores);

        jMenu1.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        jMenu12.setText("Produtos");

        menuCadProdutos.setText("Cadastrar");
        jMenu12.add(menuCadProdutos);

        menuConProdutos.setText("Consultar");
        jMenu12.add(menuConProdutos);

        jMenu1.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        jMenu13.setText("Serviços");

        menuCadServicos.setText("Cadastrar");
        jMenu13.add(menuCadServicos);

        menuConServicos.setText("Consultar");
        jMenu13.add(menuConServicos);

        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        jMenu2.setText("Reservas   |");

        menuCadReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_checkin.png"))); // NOI18N
        menuCadReservas.setText("Cadastrar Reserva");
        jMenu2.add(menuCadReservas);

        menuConReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Con_checkin.png"))); // NOI18N
        menuConReservas.setText("Consultar Reserva");
        jMenu2.add(menuConReservas);

        menuFinReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_checkout.png"))); // NOI18N
        menuFinReservas.setText("Finalizar Reserva");
        jMenu2.add(menuFinReservas);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        jMenu3.setText("Vendas   |");

        menuVenProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        menuVenProdutos.setText("Produtos");
        jMenu3.add(menuVenProdutos);

        menuVenServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        menuVenServicos.setText("Serviços");
        menuVenServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVenServicosActionPerformed(evt);
            }
        });
        jMenu3.add(menuVenServicos);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        jMenu4.setText("Financeiro   |");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_paga.png"))); // NOI18N
        jMenu14.setText("Contas a Pagar");

        menuCadConPagar.setText("Cadastrar");
        jMenu14.add(menuCadConPagar);

        menuConConPagar.setText("Consultar");
        jMenu14.add(menuConConPagar);

        jMenu4.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_recebe.png"))); // NOI18N
        jMenu15.setText("Contas a Receber");

        menuCadConReceber.setText("Cadastrar");
        jMenu15.add(menuCadConReceber);

        menuConConReceber.setText("Consultar");
        jMenu15.add(menuConConReceber);

        jMenu4.add(jMenu15);

        menuBalanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_balanco.png"))); // NOI18N
        menuBalanco.setText("Balanço");
        jMenu4.add(menuBalanco);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenu5.setText("Relatório   |");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem1.setText("Hospedes");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem2.setText("Funcionários");
        jMenu5.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenuItem3.setText("Fornecedores");
        jMenu5.add(jMenuItem3);

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenu16.setText("Financeiro");

        menuRelaFinContPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        menuRelaFinContPagar.setText("Contas a Pagar");
        jMenu16.add(menuRelaFinContPagar);

        menuRelaFinContReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        menuRelaFinContReceber.setText("Contas a Receber");
        menuRelaFinContReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelaFinContReceberActionPerformed(evt);
            }
        });
        jMenu16.add(menuRelaFinContReceber);

        menuRelaFinBalanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        menuRelaFinBalanco.setText("Balanço");
        jMenu16.add(menuRelaFinBalanco);

        jMenu5.add(jMenu16);

        jMenu17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        jMenu17.setText("Reservas");

        menuRelaResQDisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResQDisp.setText("Quartos Disponiveis");
        menuRelaResQDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelaResQDispActionPerformed(evt);
            }
        });
        jMenu17.add(menuRelaResQDisp);

        menuRelaResQOcup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResQOcup.setText("Quartos Ocupados");
        jMenu17.add(menuRelaResQOcup);

        menuRelaResRFut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_reserva.png"))); // NOI18N
        menuRelaResRFut.setText("Reservas Futuras");
        jMenu17.add(menuRelaResRFut);

        jMenu5.add(jMenu17);

        jMenu18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        jMenu18.setText("Vendas");

        menuRelaVenProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        menuRelaVenProdutos.setText("Produtos");
        jMenu18.add(menuRelaVenProdutos);

        menuRelaVenServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_rela_financeiro.png"))); // NOI18N
        menuRelaVenServicos.setText("Serviços");
        jMenu18.add(menuRelaVenServicos);

        jMenu5.add(jMenu18);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        jMenu7.setText("Segurança   |");

        menuFazBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_backup.png"))); // NOI18N
        menuFazBackup.setText("Fazer Backup");
        jMenu7.add(menuFazBackup);

        menuResBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_restaura.png"))); // NOI18N
        menuResBackup.setText("Restaurar Backup");
        jMenu7.add(menuResBackup);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        jMenu8.setText("Ferramentas   |");

        jMenu19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img.png"))); // NOI18N
        jMenu19.setText("Tela de Fundo");

        menuFerraTelaAddFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_add.png"))); // NOI18N
        menuFerraTelaAddFundo.setText("Add Imagem");
        jMenu19.add(menuFerraTelaAddFundo);

        menuFerraTelaRemovImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_remove.png"))); // NOI18N
        menuFerraTelaRemovImg.setText("Remover Imagem");
        jMenu19.add(menuFerraTelaRemovImg);

        menuFerraTelaResPadrao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_img_padrao.png"))); // NOI18N
        menuFerraTelaResPadrao.setText("Restaurar Padrão");
        jMenu19.add(menuFerraTelaResPadrao);

        jMenu8.add(jMenu19);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_sistema.png"))); // NOI18N
        jMenuItem6.setText("Sobre o Sistema");
        jMenu8.add(jMenuItem6);

        jMenuBar1.add(jMenu8);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVenServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVenServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVenServicosActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void menuRelaFinContReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelaFinContReceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelaFinContReceberActionPerformed

    private void menuRelaResQDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelaResQDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelaResQDispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuBalanco;
    private javax.swing.JMenuItem menuCadConPagar;
    private javax.swing.JMenuItem menuCadConReceber;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospedes;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadReservas;
    private javax.swing.JMenuItem menuCadServicos;
    private javax.swing.JMenuItem menuConConPagar;
    private javax.swing.JMenuItem menuConConReceber;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospedes;
    private javax.swing.JMenuItem menuConProdutos;
    private javax.swing.JMenuItem menuConQuartos;
    private javax.swing.JMenuItem menuConReservas;
    private javax.swing.JMenuItem menuConServicos;
    private javax.swing.JMenuItem menuFazBackup;
    private javax.swing.JMenuItem menuFerraTelaAddFundo;
    private javax.swing.JMenuItem menuFerraTelaRemovImg;
    private javax.swing.JMenuItem menuFerraTelaResPadrao;
    private javax.swing.JMenuItem menuFinReservas;
    private javax.swing.JMenuItem menuRelaFinBalanco;
    private javax.swing.JMenuItem menuRelaFinContPagar;
    private javax.swing.JMenuItem menuRelaFinContReceber;
    private javax.swing.JMenuItem menuRelaResQDisp;
    private javax.swing.JMenuItem menuRelaResQOcup;
    private javax.swing.JMenuItem menuRelaResRFut;
    private javax.swing.JMenuItem menuRelaVenProdutos;
    private javax.swing.JMenuItem menuRelaVenServicos;
    private javax.swing.JMenuItem menuResBackup;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuVenProdutos;
    private javax.swing.JMenuItem menuVenServicos;
    // End of variables declaration//GEN-END:variables
}
